syntax = "proto3";

option csharp_namespace = "Virtava.DataFormatModules.ArkitBlendshapes";

message Blendshapes {
    float browDownLeft = 1; 
    float browDownRight = 2; 
    float browInnerUp = 3; 
    float browOuterUpLeft = 4; 
    float browOuterUpRight = 5; 
    float cheekPuff = 6; 
    float cheekSquintLeft = 7; 
    float cheekSquintRight = 8; 
    float eyeBlinkLeft = 9; 
    float eyeBlinkRight = 10;
    float eyeLookDownLeft = 11;
    float eyeLookDownRight = 12;
    float eyeLookInLeft = 13;
    float eyeLookInRight = 14;
    float eyeLookOutLeft = 15;
    float eyeLookOutRight = 16;
    float eyeLookUpLeft = 17;
    float eyeLookUpRight = 18;
    float eyeSquintLeft = 19;
    float eyeSquintRight = 20;
    float eyeWideLeft = 21;
    float eyeWideRight = 22;
    float jawForward = 23;
    float jawLeft = 24;
    float jawOpen = 25;
    float jawRight = 26;
    float mouthClose = 27;
    float mouthDimpleLeft = 28;
    float mouthDimpleRight = 29;
    float mouthFrownLeft = 30;
    float mouthFrownRight = 31;
    float mouthFunnel = 32;
    float mouthLeft = 33;
    float mouthLowerDownLeft = 34;
    float mouthLowerDownRight = 35;
    float mouthPressLeft = 36;
    float mouthPressRight = 37;
    float mouthPucker = 38;
    float mouthRight = 39;
    float mouthRollLower = 40;
    float mouthRollUpper = 41;
    float mouthShrugLower = 42;
    float mouthShrugUpper = 43;
    float mouthSmileLeft = 44;
    float mouthSmileRight = 45;
    float mouthStretchLeft = 46;
    float mouthStretchRight = 47;
    float mouthUpperUpLeft = 48;
    float mouthUpperUpRight = 49;
    float noseSneerLeft = 50;
    float noseSneerRight = 51;
    float tongueOut = 52;
}

message ArkitBlendshapesResult {
    bool trackingSucceded = 1;
    Blendshapes blendshapes = 2;
}