# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: landmarks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flandmarks.proto\"[\n\x17NormalizedLandmarkPoint\x12\x0e\n\x01x\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x0e\n\x01z\x18\x03 \x01(\x02H\x02\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_yB\x04\n\x02_z\"H\n\x1cNormalizedLandmarkPointsList\x12(\n\x06points\x18\x01 \x03(\x0b\x32\x18.NormalizedLandmarkPointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'landmarks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NORMALIZEDLANDMARKPOINT']._serialized_start=19
  _globals['_NORMALIZEDLANDMARKPOINT']._serialized_end=110
  _globals['_NORMALIZEDLANDMARKPOINTSLIST']._serialized_start=112
  _globals['_NORMALIZEDLANDMARKPOINTSLIST']._serialized_end=184
# @@protoc_insertion_point(module_scope)
