<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
    <PackageReference Include="NetMQ" Version="4.0.2.2" />
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>VirtavaClient</PackageId>
    <Version>0.0.1</Version>
    <Authors>Denys Zatolochny</Authors>
    <Company>Neutrals</Company>
  </PropertyGroup>


</Project>
