from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Blendshapes(_message.Message):
    __slots__ = ("browDownLeft", "browDownRight", "browInnerUp", "browOuterUpLeft", "browOuterUpRight", "cheekPuff", "cheekSquintLeft", "cheekSquintRight", "eyeBlinkLeft", "eyeBlinkRight", "eyeLookDownLeft", "eyeLookDownRight", "eyeLookInLeft", "eyeLookInRight", "eyeLookOutLeft", "eyeLookOutRight", "eyeLookUpLeft", "eyeLookUpRight", "eyeSquintLeft", "eyeSquintRight", "eyeWideLeft", "eyeWideRight", "jawForward", "jawLeft", "jawOpen", "jawRight", "mouthClose", "mouthDimpleLeft", "mouthDimpleRight", "mouthFrownLeft", "mouthFrownRight", "mouthFunnel", "mouthLeft", "mouthLowerDownLeft", "mouthLowerDownRight", "mouthPressLeft", "mouthPressRight", "mouthPucker", "mouthRight", "mouthRollLower", "mouthRollUpper", "mouthShrugLower", "mouthShrugUpper", "mouthSmileLeft", "mouthSmileRight", "mouthStretchLeft", "mouthStretchRight", "mouthUpperUpLeft", "mouthUpperUpRight", "noseSneerLeft", "noseSneerRight", "tongueOut")
    BROWDOWNLEFT_FIELD_NUMBER: _ClassVar[int]
    BROWDOWNRIGHT_FIELD_NUMBER: _ClassVar[int]
    BROWINNERUP_FIELD_NUMBER: _ClassVar[int]
    BROWOUTERUPLEFT_FIELD_NUMBER: _ClassVar[int]
    BROWOUTERUPRIGHT_FIELD_NUMBER: _ClassVar[int]
    CHEEKPUFF_FIELD_NUMBER: _ClassVar[int]
    CHEEKSQUINTLEFT_FIELD_NUMBER: _ClassVar[int]
    CHEEKSQUINTRIGHT_FIELD_NUMBER: _ClassVar[int]
    EYEBLINKLEFT_FIELD_NUMBER: _ClassVar[int]
    EYEBLINKRIGHT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKDOWNLEFT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKDOWNRIGHT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKINLEFT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKINRIGHT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKOUTLEFT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKOUTRIGHT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKUPLEFT_FIELD_NUMBER: _ClassVar[int]
    EYELOOKUPRIGHT_FIELD_NUMBER: _ClassVar[int]
    EYESQUINTLEFT_FIELD_NUMBER: _ClassVar[int]
    EYESQUINTRIGHT_FIELD_NUMBER: _ClassVar[int]
    EYEWIDELEFT_FIELD_NUMBER: _ClassVar[int]
    EYEWIDERIGHT_FIELD_NUMBER: _ClassVar[int]
    JAWFORWARD_FIELD_NUMBER: _ClassVar[int]
    JAWLEFT_FIELD_NUMBER: _ClassVar[int]
    JAWOPEN_FIELD_NUMBER: _ClassVar[int]
    JAWRIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHCLOSE_FIELD_NUMBER: _ClassVar[int]
    MOUTHDIMPLELEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHDIMPLERIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHFROWNLEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHFROWNRIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHFUNNEL_FIELD_NUMBER: _ClassVar[int]
    MOUTHLEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHLOWERDOWNLEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHLOWERDOWNRIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHPRESSLEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHPRESSRIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHPUCKER_FIELD_NUMBER: _ClassVar[int]
    MOUTHRIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHROLLLOWER_FIELD_NUMBER: _ClassVar[int]
    MOUTHROLLUPPER_FIELD_NUMBER: _ClassVar[int]
    MOUTHSHRUGLOWER_FIELD_NUMBER: _ClassVar[int]
    MOUTHSHRUGUPPER_FIELD_NUMBER: _ClassVar[int]
    MOUTHSMILELEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHSMILERIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHSTRETCHLEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHSTRETCHRIGHT_FIELD_NUMBER: _ClassVar[int]
    MOUTHUPPERUPLEFT_FIELD_NUMBER: _ClassVar[int]
    MOUTHUPPERUPRIGHT_FIELD_NUMBER: _ClassVar[int]
    NOSESNEERLEFT_FIELD_NUMBER: _ClassVar[int]
    NOSESNEERRIGHT_FIELD_NUMBER: _ClassVar[int]
    TONGUEOUT_FIELD_NUMBER: _ClassVar[int]
    browDownLeft: float
    browDownRight: float
    browInnerUp: float
    browOuterUpLeft: float
    browOuterUpRight: float
    cheekPuff: float
    cheekSquintLeft: float
    cheekSquintRight: float
    eyeBlinkLeft: float
    eyeBlinkRight: float
    eyeLookDownLeft: float
    eyeLookDownRight: float
    eyeLookInLeft: float
    eyeLookInRight: float
    eyeLookOutLeft: float
    eyeLookOutRight: float
    eyeLookUpLeft: float
    eyeLookUpRight: float
    eyeSquintLeft: float
    eyeSquintRight: float
    eyeWideLeft: float
    eyeWideRight: float
    jawForward: float
    jawLeft: float
    jawOpen: float
    jawRight: float
    mouthClose: float
    mouthDimpleLeft: float
    mouthDimpleRight: float
    mouthFrownLeft: float
    mouthFrownRight: float
    mouthFunnel: float
    mouthLeft: float
    mouthLowerDownLeft: float
    mouthLowerDownRight: float
    mouthPressLeft: float
    mouthPressRight: float
    mouthPucker: float
    mouthRight: float
    mouthRollLower: float
    mouthRollUpper: float
    mouthShrugLower: float
    mouthShrugUpper: float
    mouthSmileLeft: float
    mouthSmileRight: float
    mouthStretchLeft: float
    mouthStretchRight: float
    mouthUpperUpLeft: float
    mouthUpperUpRight: float
    noseSneerLeft: float
    noseSneerRight: float
    tongueOut: float
    def __init__(self, browDownLeft: _Optional[float] = ..., browDownRight: _Optional[float] = ..., browInnerUp: _Optional[float] = ..., browOuterUpLeft: _Optional[float] = ..., browOuterUpRight: _Optional[float] = ..., cheekPuff: _Optional[float] = ..., cheekSquintLeft: _Optional[float] = ..., cheekSquintRight: _Optional[float] = ..., eyeBlinkLeft: _Optional[float] = ..., eyeBlinkRight: _Optional[float] = ..., eyeLookDownLeft: _Optional[float] = ..., eyeLookDownRight: _Optional[float] = ..., eyeLookInLeft: _Optional[float] = ..., eyeLookInRight: _Optional[float] = ..., eyeLookOutLeft: _Optional[float] = ..., eyeLookOutRight: _Optional[float] = ..., eyeLookUpLeft: _Optional[float] = ..., eyeLookUpRight: _Optional[float] = ..., eyeSquintLeft: _Optional[float] = ..., eyeSquintRight: _Optional[float] = ..., eyeWideLeft: _Optional[float] = ..., eyeWideRight: _Optional[float] = ..., jawForward: _Optional[float] = ..., jawLeft: _Optional[float] = ..., jawOpen: _Optional[float] = ..., jawRight: _Optional[float] = ..., mouthClose: _Optional[float] = ..., mouthDimpleLeft: _Optional[float] = ..., mouthDimpleRight: _Optional[float] = ..., mouthFrownLeft: _Optional[float] = ..., mouthFrownRight: _Optional[float] = ..., mouthFunnel: _Optional[float] = ..., mouthLeft: _Optional[float] = ..., mouthLowerDownLeft: _Optional[float] = ..., mouthLowerDownRight: _Optional[float] = ..., mouthPressLeft: _Optional[float] = ..., mouthPressRight: _Optional[float] = ..., mouthPucker: _Optional[float] = ..., mouthRight: _Optional[float] = ..., mouthRollLower: _Optional[float] = ..., mouthRollUpper: _Optional[float] = ..., mouthShrugLower: _Optional[float] = ..., mouthShrugUpper: _Optional[float] = ..., mouthSmileLeft: _Optional[float] = ..., mouthSmileRight: _Optional[float] = ..., mouthStretchLeft: _Optional[float] = ..., mouthStretchRight: _Optional[float] = ..., mouthUpperUpLeft: _Optional[float] = ..., mouthUpperUpRight: _Optional[float] = ..., noseSneerLeft: _Optional[float] = ..., noseSneerRight: _Optional[float] = ..., tongueOut: _Optional[float] = ...) -> None: ...

class ArkitBlendshapesResult(_message.Message):
    __slots__ = ("trackingSucceded", "blendshapes")
    TRACKINGSUCCEDED_FIELD_NUMBER: _ClassVar[int]
    BLENDSHAPES_FIELD_NUMBER: _ClassVar[int]
    trackingSucceded: bool
    blendshapes: Blendshapes
    def __init__(self, trackingSucceded: bool = ..., blendshapes: _Optional[_Union[Blendshapes, _Mapping]] = ...) -> None: ...
